[package]
name = "pixiv_downloader"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c_fixed_string = { version = "0.2", optional = true }
chrono = "0.4"
dateparser = "0.1.6"
futures-util = "0.3"
getopts = "0.2"
gettext = "0.4"
html_parser = "0.6.2"
int-enum = { version = "0.4", optional = true }
lazy_static = "1.4"
json = "0.12"
regex = "1"
reqwest = { version = "0.11", features = ["brotli", "deflate", "gzip", "rustls-tls", "socks", "stream"] }
RustyXML = "0.3"
spin_on = "0.1.1"
tokio = { version = "1.17", features = ["rt", "macros", "rt-multi-thread", "time"] }
urlparse = "0.7"
utf16string = { version= "0.2", optional = true }

[build-dependencies]
cmake = "0.1"
bindgen = "0.59"

[features]
exif = ["c_fixed_string", "link-cplusplus", "int-enum", "utf16string"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winnls", "stringapiset"] }

[target.'cfg(target_env = "gnu")'.dependencies]
link-cplusplus = { version = "1.0", features = ["libstdc++"], optional = true }
