name: Docker Image Deploy

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/CI.yaml'
      - '.github/workflows/github-pages.yaml'
      - 'doc/**'
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: lifegpc
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: lifegpc/pixiv_downloader
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
